//! Deterministically regenerates the checked-in Linux native parser seeds.
//!
//! Run with `cargo run --manifest-path fuzz/Cargo.toml --bin
//! generate_linux_native_seeds` from the repository root. The records use
//! native-endian Linux fields, so they are intentionally generated by Rust
//! rather than maintained as hand-edited hex or text files.

use std::{fs, io, path::Path};

const NAME_OFFSET: usize = 19;
const DT_DIR: u8 = 4;
const DT_REG: u8 = 8;

fn record(name: &[u8], directory_type: u8) -> Vec<u8> {
    let length = (NAME_OFFSET + name.len() + 1 + 7) & !7;
    let mut record = vec![0_u8; length];
    record[16..18].copy_from_slice(&(length as u16).to_ne_bytes());
    record[18] = directory_type;
    record[NAME_OFFSET..NAME_OFFSET + name.len()].copy_from_slice(name);
    record
}

fn write(root: &Path, relative: &str, bytes: Vec<u8>) -> io::Result<()> {
    fs::write(root.join(relative), bytes)
}

fn main() -> io::Result<()> {
    let root = std::env::current_dir()?;
    let long_name = vec![b'x'; 255];
    write(
        &root,
        "fuzz/corpus/linux_dirent_parser/single-regular",
        record(b"one", DT_REG),
    )?;
    write(
        &root,
        "fuzz/corpus/linux_dirent_parser/minimal-name",
        record(b"a", DT_REG),
    )?;
    let mut multi = record(b"nested", DT_DIR);
    multi.extend(record(b"file", DT_REG));
    write(
        &root,
        "fuzz/corpus/linux_dirent_parser/multi-directory-regular",
        multi,
    )?;
    write(
        &root,
        "fuzz/corpus/linux_dirent_parser/long-name",
        record(&long_name, DT_REG),
    )
}
