//! Deterministically regenerates the checked-in macOS native parser seeds.
//!
//! Run with `cargo run --manifest-path fuzz/Cargo.toml --bin
//! generate_macos_native_seeds` from the repository root. The records use
//! native-endian Darwin fields, so they are intentionally generated by Rust
//! rather than maintained as hand-edited hex or text files.

use std::{fs, io, path::Path};

const NAME_OFFSET: usize = 21;
const DT_DIR: u8 = 4;
const DT_REG: u8 = 8;
const ATTR_CMN_NAME: u32 = 0x0000_0001;
const ATTR_CMN_OBJTYPE: u32 = 0x0000_0008;
const ATTR_CMN_ERROR: u32 = 0x2000_0000;
const ATTR_CMN_RETURNED_ATTRS: u32 = 0x8000_0000;
const VDIR: u32 = 2;

fn dirent_record(name: &[u8], directory_type: u8) -> Vec<u8> {
    let length = (NAME_OFFSET + name.len() + 3) & !3;
    let mut record = vec![0_u8; length];
    record[16..18].copy_from_slice(&(length as u16).to_ne_bytes());
    record[18..20].copy_from_slice(&(name.len() as u16).to_ne_bytes());
    record[20] = directory_type;
    record[NAME_OFFSET..NAME_OFFSET + name.len()].copy_from_slice(name);
    record
}

fn bulk_record(name: &[u8], object_type: Option<u32>) -> Vec<u8> {
    const ATTRIBUTE_RECORD_HEADER_SIZE: usize = 24;
    let name_reference_offset = ATTRIBUTE_RECORD_HEADER_SIZE + 4;
    let object_type_offset = name_reference_offset + 8;
    let name_offset = object_type.map_or(object_type_offset, |_| object_type_offset + 4);
    let length = name_offset + name.len() + 1;
    let mut record = vec![0_u8; length];
    record[..4].copy_from_slice(&(length as u32).to_ne_bytes());
    let attributes = ATTR_CMN_RETURNED_ATTRS
        | ATTR_CMN_ERROR
        | ATTR_CMN_NAME
        | if object_type.is_some() { ATTR_CMN_OBJTYPE } else { 0 };
    record[4..8].copy_from_slice(&attributes.to_ne_bytes());
    record[name_reference_offset..name_reference_offset + 4]
        .copy_from_slice(&((name_offset - name_reference_offset) as i32).to_ne_bytes());
    record[name_reference_offset + 4..object_type_offset]
        .copy_from_slice(&((name.len() + 1) as u32).to_ne_bytes());
    if let Some(object_type) = object_type {
        record[object_type_offset..name_offset].copy_from_slice(&object_type.to_ne_bytes());
    }
    record[name_offset..name_offset + name.len()].copy_from_slice(name);
    record
}

fn write(root: &Path, relative: &str, bytes: Vec<u8>) -> io::Result<()> {
    fs::write(root.join(relative), bytes)
}

fn main() -> io::Result<()> {
    let root = std::env::current_dir()?;
    let long_name = vec![b'x'; 255];
    write(
        &root,
        "fuzz/corpus/macos_dirent_parser/single-regular",
        dirent_record(b"one", DT_REG),
    )?;
    write(
        &root,
        "fuzz/corpus/macos_dirent_parser/minimal-name",
        dirent_record(b"a", DT_REG),
    )?;
    let mut multi = dirent_record(b"nested", DT_DIR);
    multi.extend(dirent_record(b"file", DT_REG));
    write(
        &root,
        "fuzz/corpus/macos_dirent_parser/multi-directory-regular",
        multi,
    )?;
    write(
        &root,
        "fuzz/corpus/macos_dirent_parser/long-name",
        dirent_record(&long_name, DT_REG),
    )?;
    write(
        &root,
        "fuzz/corpus/macos_bulk_record_parser/name-and-type",
        bulk_record(b"entry", Some(VDIR)),
    )?;
    write(
        &root,
        "fuzz/corpus/macos_bulk_record_parser/no-object-type",
        bulk_record(b"unknown", None),
    )?;
    write(
        &root,
        "fuzz/corpus/macos_bulk_record_parser/long-name",
        bulk_record(&long_name, Some(VDIR)),
    )
}
